version: '3.8'

services:
  php:
    image: php:apache
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - redis
    command: ["bash", "-c", "apt-get update && apt-get install -y libhiredis-dev && pecl install redis && docker-php-ext-enable redis && docker-php-ext-install mysqli pdo pdo_mysql && apache2-foreground"]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  dotnet:
    build:
      context: ./dotnetcore
      dockerfile: Dockerfile
    ports:
      - "8181:81" # Change the port to 8181 since port 81 is already used by nginx
    depends_on:
      - redis

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount the nginx.conf file
    depends_on:
      - php
      - dotnet
